export const REPORT_PRINT_DISCLAIMER =
  "Draft Vault provides supporting evidence of the writing process. It does not prove authorship with 100% certainty.";

export const REPORT_PRINT_FOOTER_ATTRIBUTION = "Generated by Draft Vault";

export const REPORT_EXPORT_TIP =
  "Tip: disable browser headers and footers in the print dialog for the cleanest PDF.";

export function formatReportGeneratedAt(date: Date = new Date()): string {
  return date.toLocaleString("en-US", {
    dateStyle: "long",
    timeStyle: "short",
  });
}

export function getVerificationStatusLabel(chainIsValid: boolean): string {
  return chainIsValid ? "Verification passed" : "Verification failed";
}
